### ISSUE TITLE
Document GFA `a` record

### ISSUE THREAD

**Issue by sjackman** [lh3/miniasm#10]
Hi, Heng. If you think that the `a` record that you've used in the GFA output of `miniasm` would be useful to others, would you like to send a pull request documenting it to https://github.com/pmelsted/GFA-spec, or document it here and I'll add it to the GFA spec? Thanks, Shaun

**Comment by lh3** [comment]
That is just a temporary field for debugging. I am likely to change its format and then will consider to standardize it.

**Comment by sjackman** [comment]
Okay. Thanks, Heng.
