### ISSUE TITLE
sam2paf javascript code

### ISSUE THREAD

**Issue by cjain7** [lh3/miniasm#15]
Hi, 

I am trying to run the sam2paf javascript code to do the format conversion. Due to no prior experience with javascript, I have been following multiple ways, mentioned online to get the code running on mac/linux, but saw no success so far. 
Do you have the conversion script written in other language? or can you supply some tips on how to compile/execute this file?

On mac, I tried the following:

`/System/Library/Frameworks/JavaScriptCore.framework/Versions/Current/Resources/jsc miniasm/misc/sam2paf.js bwa.30K.sam`

`Exception: ReferenceError: Can't find variable: File`
`global code@miniasm/misc/sam2paf.js:1:63`
`Could not open file: bwa.30K.sam`

**Comment by lh3** [comment]
Well, that script is not intended for end users. If you want to try anyway, download [k8](https://github.com/attractivechaos/k8/) precompiled binary [here](https://github.com/attractivechaos/k8/releases) and run the script with:
```sh
k8-linux sam2paf.js <in.sam>
```
Let me know if that works.

**Comment by cjain7** [comment]
Works, thanks.
