### ISSUE TITLE
Parameter tweaking for assembling error-corrected reads

### ISSUE THREAD

**Issue by suryasaha** [lh3/miniasm#16]
I am assembling error corrected pacbio reads from canu for a heterogeneous sample (pool of sexually reproducing individuals) using parameters in the README. Raw coverage was 80X that reduces to 26X after correction. I don't get any better assemblies with the error corrected reads.

Would you recommend any alternative parameter choices when handling error corrected pacbio reads? Thanks

**Comment by lh3** [comment]
> I don't get any better assemblies with the error corrected reads.

That was also my experience on bacterial assembly: N50 and misassembly rate are about the same with or without PBcR/falcon_sense error correction. I tried different settings that time, but the final assembly was not obviously improved given error corrected reads.

**Comment by suryasaha** [comment]
Same experience here but this is an insect genome. Is there any setting to tweak minimap to handle a heterozygous sample?

**Comment by lh3** [comment]
Probably not. The error rate of error corrected reads and minimap's resolution of sequence differences are higher than heterozygosity.

**Comment by suryasaha** [comment]
Thank you for the quick responses @lh3 !
