### ISSUE TITLE
bad gateway for test data

### ISSUE THREAD

**Issue by ekg** [lh3/miniasm#4]
Hi @lh3,

I get this error when trying to download the test data:

```bash
➜  minis  wget -O reads.fa http://nanopore.climb-radosgw01.bham.ac.uk/MAP006-1_2D_pass.fasta
--2015-11-27 15:23:33--  http://nanopore.climb-radosgw01.bham.ac.uk/MAP006-1_2D_pass.fasta
Resolving nanopore.climb-radosgw01.bham.ac.uk (nanopore.climb-radosgw01.bham.ac.uk)... 147.188.173.15
Connecting to nanopore.climb-radosgw01.bham.ac.uk (nanopore.climb-radosgw01.bham.ac.uk)|147.188.173.15|:80... connected.
HTTP request sent, awaiting response... 502 Bad Gateway
2015-11-27 15:23:33 ERROR 502: Bad Gateway.
```

Looks like this isn't up: http://nanopore.climb-radosgw01.bham.ac.uk/

Is there another suitable public dataset we could use, or could we host this elsewhere?

**Comment by lh3** [comment]
Try [the example data set](http://www.cbcb.umd.edu/software/PBcR/data/selfSampleData.tar.gz) from PBcR.

**Comment by lh3** [comment]
README updated. Also updated the demo scripts in the `misc/` directory.

**Comment by nickloman** [comment]
Sorry about that, can you use this instead:

http://s3.climb.ac.uk/nanopore/MAP006-1_2D_pass.fasta

Also other links updated:

http://s3.climb.ac.uk/nanopore/MAP006-2_2D_pass.fasta
http://s3.climb.ac.uk/nanopore/MAP006-PCR-1_2D_pass.fasta
http://s3.climb.ac.uk/nanopore/MAP006-PCR-2_2D_pass.fasta
