### ISSUE TITLE
High scoring segment pairs

### ISSUE THREAD

**Issue by rehab-fouad** [lh3/miniasm#40]
How to calculate high scoring segment pairs with minimap2 for nanopore cDNA reads?

**Comment by lh3** [comment]
What do you mean by "high scoring segment pairs"? What do you want to do?

**Comment by rehab-fouad** [comment]
I want to know the length and numbers of segment in per read that mapped to the reference without gaps or mismatches

**Comment by lh3** [comment]
Sorry. You can't do that with minimap2.

**Comment by rehab-fouad** [comment]
at the link you sent me about fap
https://lh3.github.io/minimap2/minimap2.html#10
there is a description of ms; which is the maximum scoring segment. but in the output file, I got I don't get this column. do you have any idea how can I get this?

**Comment by rehab-fouad** [comment]
or which tool I can use to get this value from minimap output file?
