### ISSUE TITLE
Please tag a stable release

### ISSUE THREAD

**Issue by sjackman** [lh3/miniasm#43]
The option `-R` was included in r131, and the most recent tagged release is 0.2 r128. Could you please tag a new stable release that includes the `-R` option?

```
miniasm: illegal option -- R
```

Currently `miniasm -R` prints a warning and continues. Could this please instead exit with an error?

Thanks, Heng!

**Comment by sjackman** [comment]
Bump. Time to tag miniasm 0.3, Heng?

**Comment by bioteksampath** [comment]
I also not able to access the R -option thought my miniasm 0.2-r128.
Since my run with miniasm segfaulted, it would be great to have this option working! 
Thanks 
Sam

**Comment by sjackman** [comment]
@bioteksampath Hi, Sam. Here's the related issue for Miniasm segfaulting: https://github.com/lh3/miniasm/issues/48

**Comment by lh3** [comment]
Done. Sorry for the delay.

**Comment by sjackman** [comment]
Thanks, Heng!
