### ISSUE TITLE
No sequences in gfa - unable to convert to fasta

### ISSUE THREAD

**Issue by lpryszcz** [lh3/miniasm#45]
Hi, how do you convert .gfa to .fasta? I've found a few posts recommending awk one-liner, but there are no sequences in .gfa. 

```
awk '/^S/{print ">"$2"\n"$3}' run.gfa | head
>utg000001l
*
>utg000002l
*
>utg000003l
*
>utg000004l
*
>utg000005l
*

```

**Comment by lh3** [comment]
Use `miniasm -f reads.fq overlap.paf`
