### ISSUE TITLE
Do you keep on tagging releases

### ISSUE THREAD

**Issue by tillea** [lh3/miniasm#51]
Hi,
Debian has packaged the released version 0.2 of miniasm since we (the Debian maintainers) trust what software authors are marking as "release with distribution quality".  Recently I've found some software (Unicycler) which ships with a code copy of the latest miniasm release.  This made me wonder whether you consider every commit as some releasable state that can be distributed to the users.  It would be nice if you could clarify this situation by either keep on marking releases with tags or explain somewhere in the docs that users are supposed to use the latest Git commit.  I personally would prefer the first option (release tags) since it is more explicit.
Kind regards, Andreas.

**Comment by lh3** [comment]
Sorry for the delay. I have tagged a new release v0.3. This release has largely been the github HEAD for a couple of years and should be fairly stable.

**Comment by tillea** [comment]
On Mon, Jul 23, 2018 at 06:59:20PM -0700, Heng Li wrote:
> Sorry for the delay. I have tagged a new release v0.3. This release has largely been the github HEAD for a couple of years and should be fairly stable.
Thanks.  I've uploaded miniasm 0.3 to Debian.  Andreas.
