### ISSUE TITLE
Minimap or Minimap2

### ISSUE THREAD

**Issue by jjkoehorst** [lh3/miniasm#53]
The readme is talking about minimap but minimap2 has been released. Is it possible to just replace minimap by minimap2 or does it require more tweaks?

```
# Download sample PacBio from the PBcR website
wget -O- http://www.cbcb.umd.edu/software/PBcR/data/selfSampleData.tar.gz | tar zxf -
ln -s selfSampleData/pacbio_filtered.fastq reads.fq
# Install minimap and miniasm (requiring gcc and zlib)
git clone https://github.com/lh3/minimap && (cd minimap && make)
git clone https://github.com/lh3/miniasm && (cd miniasm && make)
# Overlap
minimap/minimap -Sw5 -L100 -m0 -t8 reads.fq reads.fq | gzip -1 > reads.paf.gz
# Layout
miniasm/miniasm -f reads.fq reads.paf.gz > reads.gfa
```

**Comment by apredeus** [comment]
Yeah, I would like to ask the same thing.

**Comment by lh3** [comment]
README updated. The minimap2 command line is different.

**Comment by apredeus** [comment]
Is it on purpose that you have used -x map-pb when calculating overlap? I thought that's what ava-bp was for. 

Thanks again!

**Comment by lh3** [comment]
It should `ava-ont`. README updated. Thank you.
