### ISSUE TITLE
Quality scores  during mapping

### ISSUE THREAD

**Issue by ardakdemir** [lh3/miniasm#67]
I have a question about the the implementation. Are you making use of the quality scores associated with each read during mapping with minimap2 ? In other words does the way we calculate and write  the quality scores  given in the fastq files affect the performance of the mapper or the overall assembly process?

**Comment by lh3** [comment]
No, quality scores are not used.

**Comment by ahcm** [comment]
Can you elaborate on why? Are they not that useful?
