### ISSUE TITLE
how to calculated identity?

### ISSUE THREAD

**Issue by LinXialab** [lh3/miniasm#69]
Hi,

Recently, we are comparing minimap2 and NGMLR.
Could you please tell us how does the number followed "dv:f:" generate?
For NGMLR, Fritz suggested us calculated the identity as follow:
identity = (the number of sequence matches)/(the total number of sequence matches, mismatches, insertions and deletions in the alignment).

Looking forward your reply!
Lin

**Comment by lh3** [comment]
Please create an issue at the minimap2 repo.
