### ISSUE TITLE
PAF end coordinates

### ISSUE THREAD

**Issue by johnomics** [lh3/miniasm#72]
The PAF documentation https://github.com/lh3/miniasm/blob/master/PAF.md says start and end coordinates are both 0-based, but in minimap2 alignments I see end coordinates that equal the length of the input sequence, eg:

```
tig00000001	57346	0	12636	+	tig00000002	30918	18322	30918	12158	12661	0
```

Does this mean the end coordinates are non-inclusive? So the above alignment, 1-based and inclusive, would include bases 1-12636 of tig00000001 and bases 18323-30918 of tig00000002? Please could you clarify this in PAF.md?

Thanks
John

**Comment by lh3** [comment]
These are BED-like intervals. I have just made a change to clarify this.

**Comment by johnomics** [comment]
Thanks - please could you update the target fields as well?
