### ISSUE TITLE
PAF Format detail 

### ISSUE THREAD

**Issue by sd880131** [lh3/miniasm#86]
Hi, I'm not sure what does the "Alignment block length" means. I have a paf like this "cc8e67f7-a22b-40c7-acdb-2ec1ed779e2e    3076    7       3053    +       Tu6     627309815       68028982        68032161   2378    3181    60      tp:A:P  cm:i:336        s1:i:2366       s2:i:215        dv:f:0.0338". It's seems that alignment block length is larger than query sequence length. where should I get more detail information  of the PAF file?

**Comment by lh3** [comment]
Block length includes insertions and deletions. That is the blast definition.
