### ISSUE TITLE
Assemble of DNA and RNA amplicons from PacBio run

### ISSUE THREAD

**Issue by s-t-calus** [lh3/miniasm#92]
I am trying to combine data from two PacBio runs: DNA (10kb) + cDNA (10kb), these regions overlap each other partially and I would like to phase them based on short-tandem repeats and exonic SNP/fingerprint to genomic exon+intron SNP fingerprints to identify intronic SNP and a number of tandem repeats that are separated by >150kb from each other. cDNA was used to bring STR's + exonic SNP closer to each other.

Do you think miniasm could assemble DNA (intronic and exonic) + RNA/cDNA reads (exonic) into a graph where we could:
phase the number of STR's + exonic SNP (cDNA) with intronic and exonic fingerprints (DNA) based on 99-100% similarity?

If yes, which of the packages I should use, if not do you have any idea what software I should consider using e.g. UCLUST or VSEARCH for OTU binning?

**Comment by lh3** [comment]
Miniasm is not intended for amplicons.
